### ISSUE TITLE
readme-guestbook.vercel.app is not registered as an OAuth redirect domain.

### ISSUE THREAD

**Issue by vincentscode** [JasonEtco/readme-guestbook#13]
Hi Jason,

now.sh is now vercel.app and redirects https://readme-guestbook.now.sh/ to https://readme-guestbook.vercel.app/.
This new domain does not seem to be registered in firebase and due to that the website does not work anymore.
The login popup closes instantly and produces the following error:
```json
{
    "code": "auth/unauthorized-domain",
    "message": "This domain (readme-guestbook.vercel.app) is not authorized to run this operation. Add it to the OAuth redirect domains list in the Firebase console -> Auth section -> Sign in method tab."
}
```

**Comment by JasonEtco** [comment]
Thanks @vincentscode, fixed! ✨
